apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: TimescaleDB
        type: postgres
        access: proxy
        url: timescaledb:5432
        database: mydb
        user: myuser
        secureJsonData:
          password: mypassword
        isDefault: false
